document.write('<header>')
document.write('<a href="index.html"><img src="./img/logo.png" alt="logo-coffee-script" id="logo"></a>')
document.write('<nav id="nav-principal"><ul class="nav-itens">')
document.write('<li class="nav-itens"><a href="./maioridade.html">Você é maior de idade?</a></li>')
document.write('<li class="nav-itens"><a href="./aprovado.html">Você está aprovado?</a></li>')
document.write(' <li class="nav-itens"><a href="./calculoimc.html">Você está dentro do peso?</a></li>')
document.write('<li class="nav-itens"><a href="./aumentosalarial.html">Você recebeu um aumento?</a></li>')
document.write('</ul></nav></header>')
