/*CREATE SCHEMA LOJA;*/

CREATE TABLE LJ_PESSOA (
  HANDLE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  CNPJCPF VARCHAR(15) NOT NULL,
  EHCLIENTE TINYINT NULL DEFAULT 0,
  EHFORNECEDOR TINYINT NULL
);

CREATE TABLE LJ_FORMAPAGAMENTO (
  HANDLE INT PRIMARY KEY  NOT NULL,
  NOME VARCHAR(255) NULL
);

CREATE TABLE LJ_CONDICAOPAGAMENTO (
  HANDLE INT PRIMARY KEY NOT NULL,
  NOME VARCHAR(255) NULL,
  QUANTIDADEPARCELA INT NULL
);

CREATE TABLE LJ_COMPRA (
  HANDLE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  FORNECEDOR INT NOT NULL,
  DATA DATE NOT NULL,
  VALORTOTAL REAL NULL,
  DOCUMENTOCOMPRA INT NULL,
  FOREIGN KEY (FORNECEDOR) REFERENCES LJ_PESSOA(HANDLE)
);

CREATE TABLE LJ_DOCUMENTOCOMPRA (
  HANDLE INT PRIMARY  KEY NOT NULL,
  VALORLIQUIDO REAL NULL,
  EMISSAO DATE NULL,
  CONDICAOPAGAMENTO INT NOT NULL,
  FORMAPAGAMENTO INT NOT NULL,
  ORDEMCOMPRA INT NOT NULL,
  FOREIGN KEY (ORDEMCOMPRA) REFERENCES LJ_COMPRA(HANDLE)
);


CREATE TABLE LJ_CATEGORIA (
  HANDLE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL
);


CREATE TABLE LJ_PRODUTO (
  HANDLE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  SKU VARCHAR(45) NOT NULL,
  CATEGORIA INT NOT NULL,
  FORNECEDOR INT NOT NULL,
  FOREIGN KEY (CATEGORIA) REFERENCES LJ_CATEGORIA(HANDLE),
  FOREIGN KEY (FORNECEDOR) REFERENCES LJ_PESSOA(HANDLE)
)
;

CREATE TABLE LJ_VENDA (
  HANDLE INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CLIENTE INT NOT NULL,
  DATA DATE NOT NULL,
  VALORTOTAL REAL NULL,
  DOCUMENTOVENDA INT NULL,
  FOREIGN KEY (CLIENTE) REFERENCES LJ_PESSOA(HANDLE)
);


CREATE TABLE LJ_DOCUMENTOVENDA (
  HANDLE INT  PRIMARY KEY NOT NULL,
  VALORLIQUIDO REAL NULL,
  EMISSAO DATE NULL,
  CONDICAOPAGAMENTO INT NOT NULL,
  FORMAPAGAMENTO INT NOT NULL,
  ORDEMVENDA INT NOT NULL,
  FOREIGN KEY (CONDICAOPAGAMENTO) REFERENCES LJ_CONDICAOPAGAMENTO(HANDLE),
  FOREIGN KEY (FORMAPAGAMENTO) REFERENCES LJ_FORMAPAGAMENTO(HANDLE),
  FOREIGN KEY (ORDEMVENDA) REFERENCES LJ_VENDA(HANDLE)
 );


CREATE TABLE LJ_COMPRAITEM (
  HANDLE INT PRIMARY KEY NOT NULL,
  COMPRA INT NOT NULL,
  PRODUTO INT NOT NULL,
  VALORUNITARIO REAL NOT NULL,
  QUANTIDADE INT NOT NULL,
  FOREIGN KEY (COMPRA) REFERENCES LJ_COMPRA(HANDLE),
  FOREIGN KEY (PRODUTO) REFERENCES LJ_PRODUTO(HANDLE)
);

CREATE TABLE LJ_VENDAITEM (
  HANDLE INT PRIMARY KEY NOT NULL,
  VENDA INT NOT NULL,
  PRODUTO INT NOT NULL,
  VALORUNITARIO REAL NOT NULL,
  QUANTIDADE INT NOT NULL,
  FOREIGN KEY (VENDA) REFERENCES LJ_VENDA(HANDLE),
  FOREIGN KEY (PRODUTO) REFERENCES LJ_PRODUTO(HANDLE)
);

ALTER TABLE LJ_VENDA ADD FOREIGN KEY (DOCUMENTOVENDA) REFERENCES LJ_DOCUMENTOVENDA(HANDLE) ;
ALTER TABLE LJ_COMPRA ADD FOREIGN KEY (DOCUMENTOCOMPRA) REFERENCES LJ_DOCUMENTOCOMPRA(HANDLE)